services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app-container-1
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=4000
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - app-network

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app-container-2
    ports:
      - "4001:4000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=4000
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - app-network

  app3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app-container-3
    ports:
      - "4002:4000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=4000
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:5
    container_name: my-mongo-container
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
